const ES=document.documentElement.lang==='es';
const header=document.querySelector('.header');
const menu=document.querySelector('.menu');
function closeMenu(){header.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent=ES?'Menú':'Menu';}
menu.addEventListener('click',()=>{const open=header.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?(ES?'Cerrar':'Close'):(ES?'Menú':'Menu');});
document.querySelectorAll('nav a').forEach(link=>link.addEventListener('click',closeMenu));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&header.classList.contains('open')){closeMenu();menu.focus();}});
// Contact form relay. Leave empty to prepare the email in the visitor's own mail app only.
const FORM_ENDPOINT='https://polancoventures-contact.polancoventures.workers.dev/';
const contactForm=document.querySelector('#contact-form');const sentPanel=document.querySelector('#sent');const submitButton=contactForm.querySelector('button[type=submit]');const formNote=contactForm.querySelector('.form-note');contactForm.querySelector('[name="t"]').value=String(Date.now());if(FORM_ENDPOINT){submitButton.textContent=ES?'Enviar presentación':'Send introduction';formNote.textContent=ES?'Sus datos van por correo a contact@polancoventures.com y se usan solo para responder. Este sitio no guarda ninguna copia; conservamos el correo hasta doce meses después de nuestro último intercambio. Si el envío falla, el correo se prepara para que usted lo envíe.':'Your details go by email to contact@polancoventures.com and are used only to reply. This website keeps no copy; we keep the email for up to twelve months after our last exchange. If sending fails, the email is prepared for you to send yourself.';}else{submitButton.textContent=ES?'Preparar presentación':'Prepare introduction';formNote.textContent=ES?'Esto prepara un correo para que lo revise y envíe. No se envía nada hasta que usted lo envíe, y este sitio no guarda ninguna copia.':'This prepares an email for you to review and send. Nothing is sent until you send it, and this website keeps no copy.';}
const help=document.querySelector('#audience-help');
const audienceHints=ES?{company:'Cuéntenos sobre el negocio, su etapa y la decisión que tiene por delante.',investor:'Comparta su enfoque de inversión, los mercados relevantes y las relaciones que desea explorar.',partner:'Cuéntenos sobre su experiencia y dónde ve una oportunidad para trabajar juntos.'}:{company:'Tell us about the business, its stage and the decision ahead.',investor:'Share your investment focus, relevant markets and the relationships you want to explore.',partner:'Tell us about your expertise and where you see an opportunity to work together.'};
function setAudience(value){const radio=contactForm.querySelector(`input[value="${value}"]`);if(!radio)return;radio.checked=true;help.textContent=audienceHints[value];document.querySelector('#email-preview').hidden=true;contactForm.hidden=false;}
contactForm.querySelectorAll('[name="audience"]').forEach(radio=>radio.addEventListener('change',()=>{help.textContent=audienceHints[radio.value];}));
document.querySelectorAll('[data-audience]').forEach(link=>link.addEventListener('click',()=>setAudience(link.dataset.audience)));
let preparedIntroduction='';
const textFields=[...contactForm.querySelectorAll('input[name],textarea[name]')].filter(f=>f.type!=='radio');function checkBlank(field){const value=field.value.trim();const min=Number(field.getAttribute('minlength'))||0;if(field.required&&!value)field.setCustomValidity(ES?'Complete este campo.':'Please complete this field.');else if(min&&value.length<min)field.setCustomValidity(ES?`Escriba al menos ${min} caracteres.`:`Please write at least ${min} characters.`);else field.setCustomValidity('');}textFields.forEach(field=>field.addEventListener('input',()=>checkBlank(field)));
contactForm.addEventListener('submit',event=>{event.preventDefault();textFields.forEach(checkBlank);if(!contactForm.reportValidity())return;const data=new FormData(contactForm);const audience=(ES?{company:'Directivo de empresa',investor:'Inversionista',partner:'Socio estratégico'}:{company:'Company leader',investor:'Investor',partner:'Strategic partner'})[data.get('audience')];const subject=ES?`Presentación de ${audience} | ${data.get('company').trim()}`:`${audience} introduction | ${data.get('company').trim()}`;preparedIntroduction=ES?`Para: contact@polancoventures.com\nAsunto: ${subject}\n\nHola, Polanco Ventures:\n\nMensaje:\n${data.get('message').trim()}\n\nNombre: ${data.get('name').trim()}\nEmpresa: ${data.get('company').trim()}\nCorreo: ${data.get('email').trim()}\nRelación: ${audience}`:`To: contact@polancoventures.com\nSubject: ${subject}\n\nHello Polanco Ventures,\n\nMessage:\n${data.get('message').trim()}\n\nName: ${data.get('name').trim()}\nCompany: ${data.get('company').trim()}\nEmail: ${data.get('email').trim()}\nRelationship: ${audience}`;document.querySelector('#email-body').textContent=preparedIntroduction;document.querySelector('#open-email').href=`mailto:contact@polancoventures.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(preparedIntroduction.split('\n\n').slice(1).join('\n\n'))}`;function showPreview(fallback){contactForm.hidden=true;const preview=document.querySelector('#email-preview');document.querySelector('#send-fallback').hidden=!fallback;preview.hidden=false;document.querySelector('#copy-status').textContent='';preview.focus();}if(!FORM_ENDPOINT){showPreview(false);return;}submitButton.disabled=true;submitButton.textContent=ES?'Enviando…':'Sending…';const payload={audience:data.get('audience'),name:data.get('name').trim(),email:data.get('email').trim(),company:data.get('company').trim(),message:data.get('message').trim(),website:data.get('website')||'',t:data.get('t')};fetch(FORM_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.ok?r.json():Promise.reject(r)).then(r=>{if(!r.ok)throw r;contactForm.hidden=true;sentPanel.hidden=false;sentPanel.focus();}).catch(()=>showPreview(true)).finally(()=>{submitButton.disabled=false;submitButton.textContent=ES?'Enviar presentación':'Send introduction';});});document.querySelector('#send-another').addEventListener('click',()=>{contactForm.reset();contactForm.querySelector('[name="t"]').value=String(Date.now());help.textContent=audienceHints.company;sentPanel.hidden=true;contactForm.hidden=false;contactForm.querySelector('[name="name"]').focus();});
document.querySelector('#edit-email').addEventListener('click',()=>{document.querySelector('#email-preview').hidden=true;contactForm.hidden=false;contactForm.querySelector('[name="name"]').focus();});
document.querySelector('#copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(preparedIntroduction);document.querySelector('#copy-status').textContent=ES?'Presentación copiada. Péguela en su servicio de correo para enviarla.':'Introduction copied. Paste it into your email service to send.';}catch{document.querySelector('#copy-status').textContent=ES?'La copia automática no está disponible. Seleccione y copie la presentación de arriba.':'Automatic copy is unavailable. Select and copy the introduction above.';const selection=window.getSelection();const range=document.createRange();range.selectNodeContents(document.querySelector('#email-body'));selection.removeAllRanges();selection.addRange(range);}});
